language: php
matrix:
  include:
    - php: 5.6
    - php: 5.5
sudo: false
before_install:
  - cd ..
  - wget --no-check-certificate https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.0.zip && unzip elasticsearch-1.7.0.zip
  - mv elasticsearch-1.7.0 elasticsearch
  - cd elasticsearch
  - bin/elasticsearch -d
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git
  - cd neos-base-distribution
  - composer require flowpack/elasticsearch-contentrepositoryadaptor dev-master
install:
  - composer install
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor
  - mv Flowpack.ElasticSearch.ContentRepositoryAdaptor neos-base-distribution/Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor
  - cd neos-base-distribution
script:
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor/Tests/Unit
  - bin/phpunit -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Flowpack.ElasticSearch.ContentRepositoryAdaptor/Tests/Functional
